export const Whatsappblocks = [
    {
        profiles: "/assets/image/svg/Designers_Corner.svg",
        holdername: "Designers Corner",
        time: "3:11 pm",
        title: "+2348128225157:",
        textmsg: "That’s a great news! Congratulations",
        unreadnotification: 197,
    },
    {
        profiles: "/assets/image/svg/daniel.svg",
        holdername: "Daniel Kalio",
        time: "2:24 pm",
        textmsg: "Oboy dash me 2k na",
    },
    {
        profiles: "/assets/image/svg/Group_class.svg",
        holdername: "Codegaminator 10.0 - UIUX Class",
        time: "1:47 pm",
        textmsg: " Bryan: Submit your figma links here before the end of...",
    },
    {
        profiles: "/assets/image/svg/beywond.svg",
        holdername: "BEYOND PEXELS",
        time: "1:22 pm",
        textmsg: " Bryan: Submit your figma links here before the end of...",
        unreadnotification: 203,
    },
    {
        profiles: "/assets/image/svg/nic.svg",
        holdername: "Gideon Nic",
        time: "1:3 pm",
        titleicons: "/assets/image/svg/cemera_icon.svg",
        textmsg: " Photo",
    },
    {
        profiles: "/assets/image/svg/benson.svg",
        holdername: "Rejoice Benson",
        time: "12:47 pm",
        titleicons: "/assets/image/svg/video_icon_gray.svg",
        textmsg: " Video",
    },
    {
        profiles: "/assets/image/svg/longs.svg",
        holdername: "Merry Longs",
        time: "12:35 pm",
        textmsg: " Hello sir I’ve sent you the link",
    },
    {
        profiles: "/assets/image/svg/goodgod.svg",
        holdername: "Goodgod UIUX",
        time: "12:1 pm",
        titleicons: "/assets/image/svg/video_icon_gray.svg",
        textmsg: "Video",
    },
    {
        profiles: "/assets/image/svg/alex.svg",
        holdername: "Alex (Tech Sis)",
        titleicons: "/assets/image/svg/video_icon_gray.svg",
        time: "11:10 am",
        textmsg: " Video",
    },
    {
        profiles: "/assets/image/svg/Designers_Corner.svg",
        holdername: "Designers Corner",
        time: "3:11 pm",
        title: "+2348128225157:",
        textmsg: "That’s a great news! Congratulations...",
    },
    {
        profiles: "/assets/image/svg/daniel.svg",
        holdername: "Daniel Kalio",
        time: "2:24 pm",
        textmsg: "Oboy dash me 2k na",
    },
    {
        profiles: "/assets/image/svg/Group_class.svg",
        holdername: "Codegaminator 10.0 - UIUX Class",
        time: "1:47 pm",
        textmsg: " Bryan: Submit your figma links here before the end of...",
    },
    {
        profiles: "/assets/image/svg/beywond.svg",
        holdername: "BEYOND PEXELS",
        time: "1:22 pm",
        textmsg: " Bryan: Submit your figma links here before the end of...",
    },
    {
        profiles: "/assets/image/svg/Designers_Corner.svg",
        holdername: "Designers Corner",
        time: "3:11 pm",
        title: "+2348128225157:",
        textmsg: "That’s a great news! Congratulations...",
        unreadnotification: 197,
    },
    {
        profiles: "/assets/image/svg/daniel.svg",
        holdername: "Daniel Kalio",
        time: "2:24 pm",
        textmsg: "Oboy dash me 2k na",
    },
    {
        profiles: "/assets/image/svg/Group_class.svg",
        holdername: "Codegaminator 10.0 - UIUX Class",
        time: "1:47 pm",
        textmsg: " Bryan: Submit your figma links here before the end of...",
    },
    {
        profiles: "/assets/image/svg/beywond.svg",
        holdername: "BEYOND PEXELS",
        time: "1:22 pm",
        textmsg: " Bryan: Submit your figma links here before the end of...",
        unreadnotification: 203,
    },
];